name: edu_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  phosphor_flutter: ^2.1.0
  lucide_icons: ^0.257.0
  flutter_localization: ^0.3.3
  material_symbols_icons: ^4.2668.0
  flutter_custom_clippers: ^2.1.0
  delayed_display: ^2.0.0
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  animated_notch_bottom_bar: ^1.0.0
  add_to_cart_animation: ^2.0.4
  flutter_staggered_animations: ^1.1.1
  get: ^4.6.5
  global_configuration: ^2.0.0-nullsafety.1
  carousel_slider: ^5.0.0
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_spinkit: ^5.1.0
  expandable: ^5.0.1
  flutter_layout_grid: ^2.0.1
  google_maps_flutter: ^2.2.5
  google_maps_flutter_android: ^2.4.9
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  url_launcher: ^6.1.7
  google_fonts: ^6.1.0
  dropdown_button2: ^2.0.0
  flutter_widget_from_html_core: ^0.16.0
  progress_dialog_null_safe: ^3.0.0
  custom_info_window: ^1.0.1
  intl: ^0.20.2
  group_button: ^5.2.2
  dropdown_search: ^6.0.2
  searchfield: ^1.2.6
  package_info_plus: ^8.3.0
  lottie: ^3.3.1
  steel_crypt: ^3.0.0
  mask_text_input_formatter: ^2.4.0
  webview_flutter: ^4.0.2
  store_redirect: ^2.0.4
  font_awesome_flutter: ^10.4.0
  device_preview: ^1.1.0
  fluttertoast: ^8.2.2
  another_flushbar: ^1.12.29
  flutter_slidable: ^4.0.0
  flex_color_scheme: ^8.2.0
  flutter_native_splash: ^2.3.6
  encrypt_shared_preferences: ^0.9.9
  sqflite: ^2.0.0+4
  path: ^1.8.0
  flutter_typeahead: ^5.2.0
  #firebase_auth: ^4.15.0
  google_sign_in: ^7.1.0
  # flutter_facebook_auth: ^7.1.1
  photo_view: ^0.15.0
  diacritic: ^0.1.3
  crypto: ^3.0.3
  image_picker: ^1.0.5
  timeline_tile: ^2.0.0
  flutter_timer_countdown: ^1.0.7
  flutter_svg: ^2.0.10+1
  marquee: ^2.2.3
  location: ^8.0.0
  geolocator: ^14.0.1
  app_settings: ^6.1.1
  fuzzy: ^0.5.0
  device_info_plus: ^11.4.0
  flutter_jailbreak_detection: ^1.10.0
  visibility_detector: ^0.4.0+2
  readmore: ^3.0.0
  animate_do: ^4.2.0
  smooth_page_indicator: ^1.2.1
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.1

icons_launcher:
  image_path: "assets/launcher_icons/ic_logo_border.png"
  platforms:
    android:
      enable: true
      image_path: "assets/launcher_icons/ic_logo_border.png"
      # adaptive_background_color: "#29377d"
      adaptive_background_image: "assets/launcher_icons/ic_background.png"
      adaptive_foreground_image: "assets/launcher_icons/ic_foreground.png"
      adaptive_round_image: "assets/launcher_icons/ic_logo_round.png"
    ios:
      enable: true
      image_path: "assets/launcher_icons/ic_logo_rectangle.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/images/
    # - assets/animations/
    # - assets/img/
    # - assets/cards/
    # - assets/icon/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#29377d"
  # background_image: "assets/icons/logo_tr.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/images/logo-lira-splash.png

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. It is supported for Android, iOS and the Web.  For Android 12,
  # see the Android 12 section below.
  # branding: "assets/icons/logo_tr.png"

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #branding_mode: bottom

  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  color_dark: "#29377d"
  # background_image_dark: "assets/icons/logo_tr.png"
  image_dark: assets/images/logo-lira-splash.png
  #branding_dark: assets/dart_dark.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    image: assets/images/logo-lira-splash.png

    # Splash screen background color.
    color: "#29377d"

    # App icon background color.
    # icon_background_color: "#17191a"

    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png

    # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
    # apply when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    image_dark: assets/images/logo-lira-splash.png
    color_dark: "#29377d"
